### ISSUE TITLE
[Jenkins] "OutOfMemoryError: Java heap space" during stash

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia-blueprint#120]
### Bug Description:
At the moment the CI is unstable again. As far as I could see building the installers itself works fine. 
However when we stash the results for further stages, Jenkins itself may fail.

Maybe we can reduce the amount of files to stash. 

Example Logs:
```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.40.38.119/10.40.38.119:57838
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1157)
		at hudson.FilePath.act(FilePath.java:1146)
		at hudson.FilePath.archive(FilePath.java:528)
		at hudson.FilePath.archive(FilePath.java:507)
		at org.jenkinsci.plugins.workflow.flow.StashManager.stash(StashManager.java:126)
		at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:115)
		at org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:103)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$698/0x000000000c287360.run(Unknown Source)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.String.toCharArray(String.java:2703)
	at org.apache.tools.ant.types.selectors.SelectorUtils.match(SelectorUtils.java:349)
	at org.apache.tools.ant.types.selectors.SelectorUtils.matchPath(SelectorUtils.java:289)
	at org.apache.tools.ant.types.selectors.TokenizedPattern.matchPath(TokenizedPattern.java:71)
	at org.apache.tools.ant.DirectoryScanner.lambda$isExcluded$7(DirectoryScanner.java:1494)
	at org.apache.tools.ant.DirectoryScanner$$Lambda$153/0x000000002c0b70f0.test(Unknown Source)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at org.apache.tools.ant.DirectoryScanner.isExcluded(DirectoryScanner.java:1494)
	at org.apache.tools.ant.DirectoryScanner.processIncluded(DirectoryScanner.java:1336)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedFile(DirectoryScanner.java:1288)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1243)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.accountForIncludedDir(DirectoryScanner.java:1313)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1262)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1195)
	at org.apache.tools.ant.DirectoryScanner.scandir(DirectoryScanner.java:1157)
	at org.apache.tools.ant.DirectoryScanner.checkIncludePatterns(DirectoryScanner.java:955)
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:913)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:528)
	at hudson.util.DirScanner$Glob.scan(DirScanner.java:141)
	at hudson.FilePath$Archive.invoke(FilePath.java:548)
	at hudson.FilePath$Archive.invoke(FilePath.java:530)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3313)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:118)
	at hudson.remoting.Engine$1$$Lambda$33/0x000000007c00a730.run(Unknown Source)
```

**Comment by marcdumais-work** [comment]
@jfaltermeier Something similar seems to intermittently happen with the "Create Mac Installer" step ultimately failing, after the installer is produced, apparently without issue. 

I wonder how you obtained the logs above?

**Comment by jfaltermeier** [comment]
> @jfaltermeier Something similar seems to intermittently happen with the "Create Mac Installer" step ultimately failing, after the installer is produced, apparently without issue.
> 
> I wonder how you obtained the logs above?

@marcdumais-work I think I downloaded the full logs of the build from Jenkins and searched for exceptions/errors. Reason for this was, that no proper error appeared in the logs of the failed stage one Jenkins, so I though something must have gone wrong in an earlier stage. 
Also I am not sure if exceptions thrown by Jenkins end up the logs of the pipeline stages or only in the full log.
