### ISSUE TITLE
IDE got stuck when  the blueprint loading sign appears on windows

### ISSUE THREAD

**Issue by cico643** [eclipse-theia/theia-blueprint#205]
### Bug Description:
IDE opens up the Getting Started page on the first start and then when I try to open a new folder, IDE got stuck on the blueprint logo loading sign stage. The issue only occurs on Windows.

### Steps to Reproduce:

1. Install theia-blueprint from scratch
2. Open IDE, Getting Started page appears on the first run.
3. Click on to the `File > Open Folder...` menu item
4. On the newly opened window create a new empty folder and choose that one as your target folder to be opened.
5. Observe that IDE gets stuck on the blueprint logo loading sign stage.

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.22.1

**Comment by jfaltermeier** [comment]
Hi, thank you for the report. I've tried to reproduce the issue in Windows 10, but was unable to do so. 
Does the problem still occur with version 1.23.0?

**Comment by cico643** [comment]
Hi @jfaltermeier, I can still reproduce on 1.23.0 with two different computers. Have you tried to reproduce the issue by removing and reinstalling your blueprint from scratch? Because it only occurs on the first run.

**Comment by jfaltermeier** [comment]
Hi, yes I've just uninstalled and reinstalled but was unable to reproduce. Could you maybe start Blueprint from a command prompt and check whether there are error logs for you that might be related?

```
user@DESKTOP-V723L64 MINGW64 /c/Program Files/Eclipse Theia/TheiaBlueprint
$ ./TheiaBlueprint.exe

Configuring to accept webviews on '^.+\.webview\..+$' hostname.
root INFO Configuration directory URI: 'file:///c%3A/Users/user/.theia'
root INFO Theia app listening on http://localhost:59574.
root WARN The local plugin referenced by local-dir:/c%3A/Users/user/.theia-blueprint/plugins does not exist.
root WARN The local plugin referenced by local-dir:/c%3A/Users/user/.theia-blueprint/extensions does not exist.
root WARN The local plugin referenced by local-dir:C:\Users\user\.theia\plugins does not exist.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path C:\Program Files\Eclipse Theia\TheiaBlueprint\resources\app\plugins\ms-vscode.js-debug
...
```

**Comment by cico643** [comment]
I got the following one.

```
root ERROR [hosted-plugin: 5800] Promise rejection not handled in one second: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered. , reason: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered.
root ERROR [hosted-plugin: 5800] With stack trace: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered.
    at t.CommandRegistryMainImpl.$executeCommand (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3052074)
    at t.RPCProtocolImpl.doInvokeHandler (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3012291)
    at t.RPCProtocolImpl.invokeHandler (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3012042)
    at t.RPCProtocolImpl.receiveRequest (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3011435)
    at t.RPCProtocolImpl.receiveOneMessage (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3010928)
    at file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3009432
    at file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:1917057
    at o.invoke (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:1917147)
    at r.fire (file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:1918892)
    at file:///C:/Users/cico6/AppData/Local/Programs/TheiaBlueprint/resources/app/lib/bundle.js:2:3013085
[11488:0304/205946.820:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: bundle.js:2:1002761
```

**Comment by jfaltermeier** [comment]
Thank you. It might be related to
```
[11488:0304/205946.820:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
Attempting to call a function in a renderer window that has been closed or released.
```
There are similar reports in electron: https://github.com/electron/electron/issues/32317

Does this message also appear in later runs where the workspace does open?
