### ISSUE TITLE
Rust extension does not work

### ISSUE THREAD

**Issue by dc740** [eclipse-theia/theia-blueprint#245]
### Bug Description:

The extension asks about installing missing rust components (I assume rust-analyzer, which does NOT show up in the extensions and it can't be found either), then the gear at the bottom keeps spinning with the "Starting" label.

### Steps to Reproduce:

1. Install the extension and open a rust project

Logs:
```2022-12-11T10:02:58.319Z root INFO [e09eb461-e3e7-4e5d-8913-7e786385526c] Start of 80 plugins: 1954.5 ms [Finished 6.681 s after frontend start]
2022-12-11T10:03:05.003Z root ERROR [hosted-plugin: 17330] Promise rejection not handled in one second: TypeError: Cannot read properties of undefined (reading 'reevaluateOnRerun') , reason: TypeError: Cannot read properties of undefined (reading 'reevaluateOnRerun')
2022-12-11T10:03:05.004Z root ERROR [hosted-plugin: 17330] With stack trace: TypeError: Cannot read properties of undefined (reading 'reevaluateOnRerun')
    at Object.fromTask (/tmp/.mount_TheiaBmuzsoM/resources/app/node_modules/@theia/plugin-ext/lib/plugin/type-converters.js:812:63)
    at TasksExtImpl.executeTask (/tmp/.mount_TheiaBmuzsoM/resources/app/node_modules/@theia/plugin-ext/lib/plugin/tasks/tasks.js:113:35)
    at Object.executeTask (/tmp/.mount_TheiaBmuzsoM/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:718:33)
    at /tmp/vscode-unpacked/rust-lang.rust-0.7.8.vsix/extension/out/src/tasks.js:109:28
    at new Promise (<anonymous>)
    at Object.<anonymous> (/tmp/vscode-unpacked/rust-lang.rust-0.7.8.vsix/extension/out/src/tasks.js:100:16)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/rust-lang.rust-0.7.8.vsix/extension/out/src/tasks.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/vscode-unpacked/rust-lang.rust-0.7.8.vsix/extension/out/src/tasks.js:4:12)

```

### Additional Information

- Operating System: Ubuntu 22.10
- Theia Version: 1.32

**Comment by vince-fugnitto** [comment]
Thank you for reporting the issue 👍 

The `rust-lang.rust` extension as pointed out is deprecated in favor of `rust-lang.rust-analyzer`. The reason `rust-analyzer` is not listed in the extensions-view is due to the fact that there is currently no compatible version of the plugin on open-vsx as the oldest version of the plugin requires an API of `^1.66.0`. 

If you want, you can always download the extension from https://open-vsx.org/extension/rust-lang/rust-analyzer and install it yourself using the `install from vsix...` command but you may encounter compatibility issues if the plugin uses newer APIs.
