### ISSUE TITLE
[Linux][1.11.0] Blueprint does not start: "cannot find fix-path'"

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#52]
### Bug Description: 

Blueprint v1.11.0 does not start. I get the same error with the `.Appimage` or the `Debian installer` version:
$ /opt/TheiaBlueprint/theia-blueprint 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'fix-path'
Require stack:
- /opt/TheiaBlueprint/resources/app/src-gen/frontend/electron-main.js
- /opt/TheiaBlueprint/resources/app/scripts/theia-electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/TheiaBlueprint/resources/app/src-gen/frontend/electron-main.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Steps to Reproduce:

1. download .deb or AppImage  from https://download.eclipse.org/theia/1.11.0/linux/)
2. chmod +x and start .AppImage or for .deb start: `/opt/TheiaBlueprint/theia-blueprint`
3.

### Additional Information

- Operating System: Ubuntu 20.04
- Theia Version: 1.11

I have not tested the Windows or MacOS packages, so I assume the issue may be Linux-specific.

**Comment by brianking** [comment]
I know this is likely fixed now, but fyi same error with  v1.11.0 on macOS
